### ISSUE TITLE
If strcpy is being used, shouldn't we include string.h?

### ISSUE THREAD

**Issue by triethyl** [debdutgoswami/data-structures-and-algorithms-pcc-cs301#1]
https://github.com/debdutgoswami/data-structures-and-algorithms-pcc-cs301/blob/624225edb2403b6a2139bedeec5868ccf55a5a9e/3rd-sem/infixTOpostfix.c#L34

The compiler complains when we try to use strcpy without including `string.h` in the file.

Fix: Add the line

```c
#include <string.h>
```
at the beginning of the file.

**Comment by debdutgoswami** [comment]
thank you pointing it out. apparently I noticed that I had a better solution to the same problem so I removed the previous file and uploaded the new one
